version: '2'

networks:
  default:

services:
  ca.poc.black.insure:
    image: hyperledger/fabric-ca:$ARCH-1.0.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.poc.black.insure
#      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/poc.black.insure-cert.pem
#      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/signingKEY31b757c04dafd7bbc97672747153fcfbae4f05d74830ecd5b2c387f8b762c12a_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.poc.black.insure-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/31b757c04dafd7bbc97672747153fcfbae4f05d74830ecd5b2c387f8b762c12a_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/poc.black.insure/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.poc.black.insure
    networks:
      - default

  orderer.black.insure:
    container_name: orderer.black.insure
    image: hyperledger/fabric-orderer:$ARCH-1.0.4
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/composer-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    networks:
      - default
    ports:
      - 7050:7050
    volumes:
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/black.insure/orderers/orderer.black.insure/msp:/etc/hyperledger/msp/orderer/msp

  peer0.poc.black.insure:
    container_name: peer0.poc.black.insure
    image: hyperledger/fabric-peer:$ARCH-1.0.4
    environment:
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.poc.black.insure
      - CORE_PEER_ADDRESS=peer0.poc.black.insure:7051
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.poc.black.insure:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.poc.black.insure:7051
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_LOCALMSPID=POCMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer.black.insure:7050
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=config_default
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-peer0.poc.black.insure:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start --peer-defaultchain=false
    networks:
      - default
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/poc.black.insure/peers/peer0.poc.black.insure/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/poc.black.insure/users:/etc/hyperledger/msp/users
        - ./crypto-config/peerOrganizations/poc.black.insure/channel:/etc/hyperledger/channel
    depends_on:
      - orderer.black.insure
      - couchdb-peer0.poc.black.insure

  peer1.poc.black.insure:
    container_name: peer1.poc.black.insure
    image: hyperledger/fabric-peer:$ARCH-1.0.4
    environment:
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.poc.black.insure
      - CORE_PEER_ADDRESS=peer1.poc.black.insure:7051
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2.poc.black.insure:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.poc.black.insure:7051
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_LOCALMSPID=POCMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer.black.insure:7050
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=config_default
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-peer1.poc.black.insure:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start --peer-defaultchain=false
    networks:
      - default
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/poc.black.insure/peers/peer1.poc.black.insure/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/poc.black.insure/users:/etc/hyperledger/msp/users
        - ./crypto-config/peerOrganizations/poc.black.insure/channel:/etc/hyperledger/channel
    depends_on:
      - orderer.black.insure
      - couchdb-peer1.poc.black.insure

  peer2.poc.black.insure:
    container_name: peer2.poc.black.insure
    image: hyperledger/fabric-peer:$ARCH-1.0.4
    environment:
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer2.poc.black.insure
      - CORE_PEER_ADDRESS=peer2.poc.black.insure:7051
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.poc.black.insure:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.poc.black.insure:7051
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_LOCALMSPID=POCMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer.black.insure:7050
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=config_default
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-peer2.poc.black.insure:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start --peer-defaultchain=false
    networks:
      - default
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./:/etc/hyperledger/configtx
        - ./crypto-config/peerOrganizations/poc.black.insure/peers/peer2.poc.black.insure/msp:/etc/hyperledger/peer/msp
        - ./crypto-config/peerOrganizations/poc.black.insure/users:/etc/hyperledger/msp/users
        - ./crypto-config/peerOrganizations/poc.black.insure/channel:/etc/hyperledger/channel
    depends_on:
      - orderer.black.insure
      - couchdb-peer2.poc.black.insure

  couchdb-peer0.poc.black.insure:
    container_name: couchdb-peer0.poc.black.insure
    image: hyperledger/fabric-couchdb:$ARCH-1.0.4
    networks:
      - default
    ports:
      - 7055:5984
    environment:
      DB_URL: http://localhost:5984/member_db

  couchdb-peer1.poc.black.insure:
    container_name: couchdb-peer1.poc.black.insure
    image: hyperledger/fabric-couchdb:$ARCH-1.0.4
    networks:
      - default
    ports:
      - 8055:5984
    environment:
      DB_URL: http://localhost:5984/member_db

  couchdb-peer2.poc.black.insure:
    container_name: couchdb-peer2.poc.black.insure
    image: hyperledger/fabric-couchdb:$ARCH-1.0.4
    networks:
      - default
    ports:
      - 9055:5984
    environment:
      DB_URL: http://localhost:5984/member_db


